doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                schema_filter: ~^(?!dbscript_string|db_version|dbscripts_on_creature_death|dbscripts_on_creature_movement|dbscripts_on_event|dbscripts_on_go_template_use|dbscripts_on_go_use|dbscripts_on_gossip|dbscripts_on_quest_end|dbscripts_on_quest_start|dbscripts_on_quest_end|dbscripts_on_quest_start|dbscripts_on_relay|dbscripts_on_spell|item_required_target|npc_trainer_template|playercreateinfo_item|spell_script_target)~
                mapping_types:
                    bit: boolean
            charactes:
                # configure these for your database server
                url: '%env(resolve:DATABASE_CHARACTERS_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            accounts:
                # configure these for your database server
                url: '%env(resolve:DATABASE_ACCOUNTS_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
